import type { Alert, AlertStats } from "./types";
import { getMockAlerts } from "./mock-data";
import { getPipelineRuns } from "../pipeline/service";
import { getAgentActivity } from "../agents/client";
import { DEFAULT_RULES, evaluateRules, type RuleEvaluationContext } from "./rules";

/**
 * Get alerts generated by evaluating alert rules
 * Falls back to mock alerts if no data sources are configured
 */
export async function getAlerts(): Promise<Alert[]> {
  const reposEnv = process.env.GITHUB_REPOS;
  
  // If no GitHub repos configured, return mock alerts
  if (!reposEnv) {
    return getMockAlerts();
  }
  
  try {
    // Gather context data for rule evaluation
    const context: RuleEvaluationContext = {
      timestamp: new Date().toISOString(),
    };

    // Fetch pipeline runs (limit to recent 50 for performance)
    try {
      context.pipelineRuns = await getPipelineRuns({ limit: 50 });
    } catch (error) {
      console.error("Failed to fetch pipeline runs for alert evaluation:", error);
    }

    // Fetch agent activity
    try {
      const agentActivity = await getAgentActivity();
      context.agents = agentActivity.agents;
    } catch (error) {
      console.error("Failed to fetch agent activity for alert evaluation:", error);
    }

    // Evaluate rules and generate alerts
    const ruleAlerts = evaluateRules(DEFAULT_RULES, context);

    // For now, keep a few mock alerts for demo purposes
    // In production, this would be database alerts + rule-generated alerts
    const mockAlerts = getMockAlerts().slice(0, 2);

    return [...ruleAlerts, ...mockAlerts];
  } catch (error) {
    console.error("Failed to generate alerts from rules:", error);
    return getMockAlerts();
  }
}

export async function getStats(): Promise<AlertStats> {
  const alerts = await getAlerts();
  
  return {
    total: alerts.length,
    active: alerts.filter(a => a.status === "active").length,
    acknowledged: alerts.filter(a => a.status === "acknowledged").length,
    resolved: alerts.filter(a => a.status === "resolved").length,
  };
}

export async function getAlert(id: string): Promise<Alert | null> {
  const alerts = await getAlerts();
  return alerts.find((a) => a.id === id) || null;
}

// TODO: Implement with Prisma for production
export async function acknowledgeAlert(id: string, acknowledgedBy: string): Promise<Alert | null> {
  console.log(`Mock: Acknowledge alert ${id} by ${acknowledgedBy}`);
  return null;
}

export async function resolveAlert(id: string): Promise<Alert | null> {
  console.log(`Mock: Resolve alert ${id}`);
  return null;
}
